<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['SalesHistory'] = array(
    'table' => 'saleshistory',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array(
        'account_id' => array(
            'required' => false,
            'name' => 'account_id',
            'vname' => 'LBL_ACCOUNT_ID',
            'type' => 'id',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => 1,
            'audited' => false,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 36,
            'size' => '20',
        ),
        'account_name' => array(
            'required' => true,
            'source' => 'non-db',
            'name' => 'account_name',
            'vname' => 'LBL_ACCOUNT_NAME',
            'type' => 'relate',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'full_text_search' => array(
                'boost' => '0',
                'enabled' => false,
            ),
            'calculated' => false,
            'len' => '255',
            'size' => '20',
            'id_name' => 'account_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'quote_id' => array(
            'required' => false,
            'name' => 'quote_id',
            'vname' => 'LBL_QUOTE_ID',
            'type' => 'id',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => 1,
            'audited' => false,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 36,
            'size' => '20',
        ),
        'quote_name' => array(
            'required' => true,
            'source' => 'non-db',
            'name' => 'quote_name',
            'vname' => 'LBL_QUOTE_NAME',
            'type' => 'relate',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'full_text_search' => array(
                'boost' => '0',
                'enabled' => false,
            ),
            'calculated' => false,
            'len' => '255',
            'size' => '20',
            'id_name' => 'quote_id',
            'ext2' => 'Quotes',
            'module' => 'Quotes',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'line_items' => array(
            'name' => 'line_items',
            'type' => 'text',
            'vname' => 'LBL_LINE_ITEMS',
            'massupdate' => false,
            'audited' => false,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'importable' => 'false',
            'studio' => false,
        ),
        'qb_id' => array(
            'name' => 'qb_id',
            'type' => 'varchar',
            'vname' => 'LBL_QB_ID',
            'reportable' => 'true',
            'default' => '',
            'importable' => 'false',
            'len' => '36',
            'size' => '36',
        ),
        'quote_type' => array(
            'name' => 'quote_type',
            'type' => 'enum',
            'vname' => 'LBL_QUOTE_TYPE',
            'reportable' => 'true',
            'options' => 'quote_maps_to_list',
            'importable' => 'false',
        ),
        'accounts' => array(
            'name' => 'accounts',
            'type' => 'link',
            'relationship' => 'accounts_saleshistory',
            'module' => 'Accounts',
            'bean_name' => 'Account',
            'source' => 'non-db',
            'vname' => 'LBL_ACCOUNT',
        ),
        'quotes' => array(
            'name' => 'quotes',
            'type' => 'link',
            'relationship' => 'quotes_saleshistory',
            'module' => 'Quotes',
            'bean_name' => 'Quote',
            'source' => 'non-db',
            'vname' => 'LBL_QUOTE',
        ),
        'qbfiles' => array(
            'name' => 'qbfiles',
            'type' => 'link',
            'relationship' => 'qbfiles_saleshistory',
            'module' => 'QBFiles',
            'bean_name' => 'QBFiles',
            'source' => 'non-db',
            'vname' => 'LBL_QBFILE',
        ),
        'qbfile_id' => array(
            'name' => 'qbfile_id',
            'rname' => 'id',
            'vname' => 'LBL_QBFILE_ID',
            'type' => 'id',
            'isnull' => 'true',
            'module' => 'QBFiles',
            'dbType' => 'id',
            'reportable' => false,
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
            'link' => 'qbfiles',
        ),
        'qbfile_name' => array(
            'name' => 'qbfile_name',
            'rname' => 'name',
            'id_name' => 'qbfile_id',
            'vname' => 'LBL_QBFILE_NAME',
            'type' => 'relate',
            'link' => 'qbfiles',
            'table' => 'qbfiles',
            'isnull' => 'true',
            'module' => 'QBFiles',
            'len' => '255',
            'source' => 'non-db',
            'unified_search' => true,
            'importable' => 'true',
            'exportable' => true,
        ),
        'duedate' => array(
            'name' => 'duedate',
            'type' => 'date',
            'vname' => 'LBL_DUEDATE',
            'reportable' => 'true',
            'default' => '',
            'importable' => 'false',
            'len' => '36',
            'size' => '36',
        ),
        'ship_date' => array(
            'name' => 'ship_date',
            'type' => 'date',
            'vname' => 'LBL_SHIP_DATE',
            'reportable' => 'true',
            'default' => '',
            'importable' => 'false',
            'len' => '36',
            'size' => '36',
        ),
        'subtotal' => array(
            'name' => 'subtotal',
            'type' => 'currency',
            'vname' => 'LBL_SUBTOTAL',
            'reportable' => 'true',
            'importable' => 'false',
            'len' => '26,6',
        ),
        'currency_id' => array(
            'name' => 'currency_id',
            'type' => 'currency_id',
            'dbType' => 'id',
            'group' => 'currency_id',
            'vname' => 'LBL_CURRENCY',
            'function' => 'getCurrencies',
            'function_bean' => 'Currencies',
            'reportable' => false,
            'comment' => 'Currency used for display purposes',
            'default' => '-99',
        ),
        'invoice_number' => array(
            'name' => 'invoice_number',
            'type' => 'varchar',
            'vname' => 'LBL_INVOICE_NUMBER',
            'reportable' => 'true',
            'default' => '',
            'importable' => 'false',
            'len' => '36',
            'size' => '36',
        ),
        'quote_number' => array(
            'name' => 'quote_number',
            'type' => 'varchar',
            'vname' => 'LBL_QUOTE_NUMBER',
            'reportable' => 'true',
            'default' => '',
            'importable' => 'false',
            'len' => '36',
            'size' => '36',
        ),
        'payments' => array(
            'name' => 'payments',
            'type' => 'link',
            'relationship' => 'saleshistory_payments',
            'source' => 'non-db',
            'module' => 'QB_Payments',
            'bean_name' => 'QB_Payments',
            'vname' => 'LBL_QB_PAYMENTS',
        ),
    ),
    'relationships' => array(
        "saleshistory_payments" => array(
	'lhs_module' => 'SalesHistory',
	'lhs_table' => 'saleshistory',
	'lhs_key' => 'id',
	'rhs_module' => 'QB_Payments',
	'rhs_table' => 'qb_payments',
	'rhs_key' => 'saleshistory_id',
	'relationship_type' => 'one-to-many',
            ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('SalesHistory', 'SalesHistory', array('basic', 'team_security', 'assignable', 'company'));
