<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'acceptable_sugar_versions' => 
  array (
    0 => '7.5.*',
    1 => '7.6.*',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'PRO',
    1 => 'CORP',
    2 => 'ENT',
    3 => 'ULT',
  ),
  'readme' => '',
  'key' => 'rt',
  'author' => '',
  'description' => 'QuickBooks and SugarCRM Integration (Plugin)',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'QB_Sugar_Sync_Plugin 2.0',
  'published_date' => '2015-12-31 12:00:00',
  'type' => 'module',
  'version' => 2.0,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'QB_Sugar_Sync_Plugin 2.0',
  'beans' => 
  array (
    array (
      'module' => 'QBFiles',
      'class' => 'QBFiles',
      'path' => 'modules/QBFiles/QBFiles.php',
      'tab' => true,
    ),
    array (
      'module' => 'QBLogs',
      'class' => 'QBLogs',
      'path' => 'modules/QBLogs/QBLogs.php',
      'tab' => true,
    ),
    array (
      'module' => 'SalesHistory',
      'class' => 'SalesHistory',
      'path' => 'modules/SalesHistory/SalesHistory.php',
      'tab' => true,
    ),
    array (
      'module' => 'QB_Payments',
      'class' => 'QB_Payments',
      'path' => 'modules/QB_Payments/QB_Payments.php',
      'tab' => true,
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    array (
      'from' => '<basepath>/copy/modules/',
      'to' => 'modules/',
    ),
    array (
      'from' => '<basepath>/copy/custom/',
      'to' => 'custom/',
    ),
  ),
          'logic_hooks' => array(
            array(
                'module' => 'Quotes',
                'hook' => 'after_save',
                'order' => 22,
                'description' => '',
                'file' => 'custom/modules/Quotes/relateQbfile.php',
                'class' => 'RelateQbfile',
                'function' => 'relateQbFileAction',
            ),
            array(
                'module' => 'Quotes',
                'hook' => 'before_save',
                'order' => 23,
                'description' => '',
                'file' => 'custom/modules/Quotes/relateQbfile.php',
                'class' => 'RelateQbfile',
                'function' => 'relateQbFileActionBeforeSave',
            ),
            array(
                'module' => 'Opportunities',
                'hook' => 'before_save',
                'order' => 1,
                'description' => 'This hook link qb file of the related Account to opp. If the User forget to link file to the opp.',
                'file' => 'custom/modules/Opportunities/relateAccQbfile.php',
                'class' => 'relateAccQbfile',
                'function' => 'relateAccQbfileAction',
            ),
            array(
                'module' => 'ProductTemplates',
                'hook' => 'before_save',
                'order' => 1,
                'description' => 'QB Product Name cannot contain a colon. The colon is a special character used to indicate a parent/child relationship.',
                'file' => 'custom/modules/ProductTemplates/validateName.php',
                'class' => 'ValidateName',
                'function' => 'ValidateNameAction',
            ),
        ),
  'layoutfields' => array(
	array(
	  'additional_fields' => array(
		'Accounts' => 'primary_contact_name',
	  ),
	),	
      array(
	  'additional_fields' => array(
		'Accounts' => 'opening_balance',
	  ),
	),
	array(
	  'additional_fields' => array(
		'Accounts' => 'qbfile_name',
	  ),
	),
 	array(
	  'additional_fields' => array(
		'Quotes' => 'qbfile_name',
	  ),
	),
 	array(
	  'additional_fields' => array(
		'Opportunities' => 'qbfile_name',
	  ),
	),
  	array(
	  'additional_fields' => array(
		'Quotes' => 'qb_item_number',
	  ),
	),
 	array(
	  'additional_fields' => array(
		'ProductTemplates' => 'qb_product_name',
	  ),
	),
      array(
          'additional_fields' => array(
                'ProductTemplates' => 'qb_item_category_c',
	  ),
	),
  ),
);
